services:
  dhis2:
    image: "${DHIS2_IMAGE:-dhis2/core:42.1.0}"
    restart: unless-stopped
    ports:
      - "${DHIS2_PORT:-8080}:8080"
    volumes:
      - ./config/dhis2/dhis.conf:/opt/dhis2/dhis.conf:ro
    environment:
      JAVA_OPTS: "-Dcontext.path='${DHIS2_CORE_CONTEXT_PATH:-}'"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -S -O /dev/null http://127.0.0.1:8080/dhis-web-login/ 2>&1| grep -q 'HTTP.*200'" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  db:
    image: ghcr.io/baosystems/postgis:13-3.4
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/:ro
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5
    security_opt:
      - no-new-privileges:true

  seed:
    image: curlimages/curl
    command:
      - "/bin/sh"
      - "-c"
      - |
        curl -X POST -s --max-time 0 -H "Authorization: Basic YWRtaW46ZGlzdHJpY3Q=" -H "Content-Type: application/json" -d @/pluginConfig.json http://dhis2:8080/api/dataStore/capture/dataEntryForms
    volumes:
      - ./config/dhis2/pluginConfig.json:/pluginConfig.json:ro
    depends_on:
      dhis2:
        condition: service_healthy

volumes:
  postgresql:
    driver: local